### ISSUE TITLE
Randomly appears HTML formatting

### ISSUE THREAD

**Issue by deadYokai** [Jeffser/Alpaca#409]
**Describe the bug**
After 32fdabd html formatting randomly appears in AI responses 

i use a GGUF

**Expected behavior**
Clear text without html stuff

**Screenshots**
![2024-12-20-194219_hyprshot](https://github.com/user-attachments/assets/13c62c35-669d-4062-bd6a-5670c037b3ae)

**Debugging information**
```
2024/12/20 19:40:37 routes.go:1259: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION:11.0.2 HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:true OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://127.0.0.1:11435 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_KV_CACHE_TYPE: OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://*] OLLAMA_SCHED_SPREAD:false ROCR_VISIBLE_DEVICES: http_proxy: https_proxy: no_proxy:]"
time=2024-12-20T19:40:37.113+02:00 level=INFO source=images.go:757 msg="total blobs: 8"
time=2024-12-20T19:40:37.114+02:00 level=INFO source=images.go:764 msg="total unused blobs removed: 0"
time=2024-12-20T19:40:37.114+02:00 level=INFO source=routes.go:1310 msg="Listening on 127.0.0.1:11435 (version 0.5.4)"
time=2024-12-20T19:40:37.114+02:00 level=DEBUG source=common.go:80 msg="runners located" dir=/usr/lib/ollama/runners
time=2024-12-20T19:40:37.114+02:00 level=DEBUG source=common.go:124 msg="availableServers : found" file=/usr/lib/ollama/runners/cpu_avx/ollama_llama_server
time=2024-12-20T19:40:37.114+02:00 level=DEBUG source=common.go:124 msg="availableServers : found" file=/usr/lib/ollama/runners/cpu_avx2/ollama_llama_server
time=2024-12-20T19:40:37.114+02:00 level=DEBUG source=common.go:124 msg="availableServers : found" file=/usr/lib/ollama/runners/rocm_avx/ollama_llama_server
time=2024-12-20T19:40:37.114+02:00 level=INFO source=routes.go:1339 msg="Dynamic LLM libraries" runners="[cpu cpu_avx cpu_avx2 rocm_avx]"
time=2024-12-20T19:40:37.114+02:00 level=DEBUG source=routes.go:1340 msg="Override detection logic by setting OLLAMA_LLM_LIBRARY"
time=2024-12-20T19:40:37.114+02:00 level=DEBUG source=sched.go:105 msg="starting llm scheduler"
time=2024-12-20T19:40:37.114+02:00 level=INFO source=gpu.go:226 msg="looking for compatible GPUs"
time=2024-12-20T19:40:37.114+02:00 level=DEBUG source=gpu.go:99 msg="searching for GPU discovery libraries for NVIDIA"
time=2024-12-20T19:40:37.114+02:00 level=DEBUG source=gpu.go:517 msg="Searching for GPU library" name=libcuda.so*
time=2024-12-20T19:40:37.114+02:00 level=DEBUG source=gpu.go:543 msg="gpu library search" globs="[/usr/lib/ollama/libcuda.so* /usr/lib/ollama/libcuda.so* /home/kitsune/libcuda.so* /usr/local/cuda*/targets/*/lib/libcuda.so* /usr/lib/*-linux-gnu/nvidia/current/libcuda.so* /usr/lib/*-linux-gnu/libcuda.so* /usr/lib/wsl/lib/libcuda.so* /usr/lib/wsl/drivers/*/libcuda.so* /opt/cuda/lib*/libcuda.so* /usr/local/cuda/lib*/libcuda.so* /usr/lib*/libcuda.so* /usr/local/lib*/libcuda.so*]"
time=2024-12-20T19:40:37.144+02:00 level=DEBUG source=gpu.go:577 msg="discovered GPU libraries" paths=[]
time=2024-12-20T19:40:37.144+02:00 level=DEBUG source=gpu.go:517 msg="Searching for GPU library" name=libcudart.so*
time=2024-12-20T19:40:37.144+02:00 level=DEBUG source=gpu.go:543 msg="gpu library search" globs="[/usr/lib/ollama/libcudart.so* /usr/lib/ollama/libcudart.so* /home/kitsune/libcudart.so* /usr/lib/ollama/libcudart.so* /usr/lib/ollama/libcudart.so* /usr/local/cuda/lib64/libcudart.so* /usr/lib/x86_64-linux-gnu/nvidia/current/libcudart.so* /usr/lib/x86_64-linux-gnu/libcudart.so* /usr/lib/wsl/lib/libcudart.so* /usr/lib/wsl/drivers/*/libcudart.so* /opt/cuda/lib64/libcudart.so* /usr/local/cuda*/targets/aarch64-linux/lib/libcudart.so* /usr/lib/aarch64-linux-gnu/nvidia/current/libcudart.so* /usr/lib/aarch64-linux-gnu/libcudart.so* /usr/local/cuda/lib*/libcudart.so* /usr/lib*/libcudart.so* /usr/local/lib*/libcudart.so*]"
time=2024-12-20T19:40:37.152+02:00 level=DEBUG source=gpu.go:577 msg="discovered GPU libraries" paths=[/opt/cuda/lib64/libcudart.so.12.6.77]
cudaSetDevice err: 35
time=2024-12-20T19:40:37.152+02:00 level=DEBUG source=gpu.go:593 msg="Unable to load cudart library /opt/cuda/lib64/libcudart.so.12.6.77: your nvidia driver is too old or missing.  If you have a CUDA GPU please upgrade to run ollama"
time=2024-12-20T19:40:37.153+02:00 level=WARN source=amd_linux.go:61 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers" error="amdgpu version file missing: /sys/module/amdgpu/version stat /sys/module/amdgpu/version: no such file or directory"
time=2024-12-20T19:40:37.153+02:00 level=DEBUG source=amd_linux.go:102 msg="evaluating amdgpu node /sys/class/kfd/kfd/topology/nodes/0/properties"
time=2024-12-20T19:40:37.153+02:00 level=DEBUG source=amd_linux.go:122 msg="detected CPU /sys/class/kfd/kfd/topology/nodes/0/properties"
time=2024-12-20T19:40:37.153+02:00 level=DEBUG source=amd_linux.go:102 msg="evaluating amdgpu node /sys/class/kfd/kfd/topology/nodes/1/properties"
time=2024-12-20T19:40:37.153+02:00 level=DEBUG source=amd_linux.go:207 msg="mapping amdgpu to drm sysfs nodes" amdgpu=/sys/class/kfd/kfd/topology/nodes/1/properties vendor=4098 device=29824 unique_id=0
time=2024-12-20T19:40:37.153+02:00 level=DEBUG source=amd_linux.go:241 msg=matched amdgpu=/sys/class/kfd/kfd/topology/nodes/1/properties drm=/sys/class/drm/card0/device
time=2024-12-20T19:40:37.153+02:00 level=DEBUG source=amd_linux.go:319 msg="amdgpu memory" gpu=0 total="8.0 GiB"
time=2024-12-20T19:40:37.153+02:00 level=DEBUG source=amd_linux.go:320 msg="amdgpu memory" gpu=0 available="7.5 GiB"
time=2024-12-20T19:40:37.153+02:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/lib/ollama"
time=2024-12-20T19:40:37.153+02:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /opt/rocm/lib"
time=2024-12-20T19:40:37.153+02:00 level=INFO source=amd_linux.go:391 msg="skipping rocm gfx compatibility check" HSA_OVERRIDE_GFX_VERSION=11.0.2
time=2024-12-20T19:40:37.153+02:00 level=INFO source=types.go:131 msg="inference compute" id=0 library=rocm variant="" compute=gfx1102 driver=0.0 name=1002:7480 total="8.0 GiB" available="7.5 GiB"
[GIN] 2024/12/20 - 19:40:37 | 200 |      256.16µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/12/20 - 19:40:37 | 200 |   17.774835ms |       127.0.0.1 | POST     "/api/show"
[GIN] 2024/12/20 - 19:40:37 | 200 |   17.885411ms |       127.0.0.1 | POST     "/api/show"
time=2024-12-20T19:40:39.013+02:00 level=DEBUG source=gpu.go:406 msg="updating system memory data" before.total="31.0 GiB" before.free="20.9 GiB" before.free_swap="18.0 GiB" now.total="31.0 GiB" now.free="20.6 GiB" now.free_swap="18.0 GiB"
time=2024-12-20T19:40:39.013+02:00 level=DEBUG source=amd_linux.go:490 msg="updating rocm free memory" gpu=0 name=1002:7480 before="7.5 GiB" now="7.5 GiB"
time=2024-12-20T19:40:39.013+02:00 level=DEBUG source=sched.go:181 msg="updating default concurrency" OLLAMA_MAX_LOADED_MODELS=0x57847a33e740 gpu_count=1
time=2024-12-20T19:40:39.047+02:00 level=DEBUG source=sched.go:224 msg="loading first model" model=/home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models/blobs/sha256-6c2f2196fefaf3eb6df34da11768c8b8646e8434cadc684e53e4d14dddfa2abc
time=2024-12-20T19:40:39.047+02:00 level=DEBUG source=memory.go:107 msg=evaluating library=rocm gpu_count=1 available="[7.5 GiB]"
time=2024-12-20T19:40:39.047+02:00 level=DEBUG source=memory.go:107 msg=evaluating library=rocm gpu_count=1 available="[7.5 GiB]"
time=2024-12-20T19:40:39.047+02:00 level=DEBUG source=memory.go:107 msg=evaluating library=rocm gpu_count=1 available="[7.5 GiB]"
time=2024-12-20T19:40:39.047+02:00 level=DEBUG source=memory.go:107 msg=evaluating library=rocm gpu_count=1 available="[7.5 GiB]"
time=2024-12-20T19:40:39.047+02:00 level=DEBUG source=gpu.go:406 msg="updating system memory data" before.total="31.0 GiB" before.free="20.6 GiB" before.free_swap="18.0 GiB" now.total="31.0 GiB" now.free="20.6 GiB" now.free_swap="18.0 GiB"
time=2024-12-20T19:40:39.047+02:00 level=DEBUG source=amd_linux.go:490 msg="updating rocm free memory" gpu=0 name=1002:7480 before="7.5 GiB" now="7.5 GiB"
time=2024-12-20T19:40:39.047+02:00 level=INFO source=server.go:104 msg="system memory" total="31.0 GiB" free="20.6 GiB" free_swap="18.0 GiB"
time=2024-12-20T19:40:39.047+02:00 level=DEBUG source=memory.go:107 msg=evaluating library=rocm gpu_count=1 available="[7.5 GiB]"
time=2024-12-20T19:40:39.048+02:00 level=INFO source=memory.go:356 msg="offload to rocm" layers.requested=-1 layers.model=43 layers.offload=38 layers.split="" memory.available="[7.5 GiB]" memory.gpu_overhead="0 B" memory.required.full="8.6 GiB" memory.required.partial="7.3 GiB" memory.required.kv="672.0 MiB" memory.required.allocations="[7.3 GiB]" memory.weights.total="6.1 GiB" memory.weights.repeating="5.4 GiB" memory.weights.nonrepeating="717.8 MiB" memory.graph.full="507.0 MiB" memory.graph.partial="1.2 GiB"
time=2024-12-20T19:40:39.048+02:00 level=DEBUG source=common.go:124 msg="availableServers : found" file=/usr/lib/ollama/runners/cpu_avx/ollama_llama_server
time=2024-12-20T19:40:39.048+02:00 level=DEBUG source=common.go:124 msg="availableServers : found" file=/usr/lib/ollama/runners/cpu_avx2/ollama_llama_server
time=2024-12-20T19:40:39.048+02:00 level=DEBUG source=common.go:124 msg="availableServers : found" file=/usr/lib/ollama/runners/rocm_avx/ollama_llama_server
time=2024-12-20T19:40:39.048+02:00 level=DEBUG source=common.go:124 msg="availableServers : found" file=/usr/lib/ollama/runners/cpu_avx/ollama_llama_server
time=2024-12-20T19:40:39.048+02:00 level=DEBUG source=common.go:124 msg="availableServers : found" file=/usr/lib/ollama/runners/cpu_avx2/ollama_llama_server
time=2024-12-20T19:40:39.048+02:00 level=DEBUG source=common.go:124 msg="availableServers : found" file=/usr/lib/ollama/runners/rocm_avx/ollama_llama_server
time=2024-12-20T19:40:39.048+02:00 level=INFO source=server.go:376 msg="starting llama server" cmd="/usr/lib/ollama/runners/rocm_avx/ollama_llama_server runner --model /home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models/blobs/sha256-6c2f2196fefaf3eb6df34da11768c8b8646e8434cadc684e53e4d14dddfa2abc --ctx-size 2048 --batch-size 512 --n-gpu-layers 38 --verbose --threads 8 --parallel 1 --port 37407"
time=2024-12-20T19:40:39.048+02:00 level=DEBUG source=server.go:393 msg=subprocess environment="[CUDA_PATH=/opt/cuda ROCM_PATH=/opt/rocm PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-ndk:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/share/dotnet:/home/kitsune/.dotnet/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/rocm/bin:/usr/lib/rustup/bin:/home/kitsune/.local/share/gem/ruby/3.0.0/bin:/home/kitsune/.local/share/JetBrains/Toolbox/scripts HSA_OVERRIDE_GFX_VERSION=11.0.2 LD_LIBRARY_PATH=/usr/lib/ollama:/usr/lib/ollama:/opt/rocm/lib:/usr/lib/ollama/runners/rocm_avx ROCR_VISIBLE_DEVICES=0]"
time=2024-12-20T19:40:39.048+02:00 level=INFO source=sched.go:449 msg="loaded runners" count=1
time=2024-12-20T19:40:39.048+02:00 level=DEBUG source=sched.go:575 msg="evaluating already loaded" model=/home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models/blobs/sha256-6c2f2196fefaf3eb6df34da11768c8b8646e8434cadc684e53e4d14dddfa2abc
time=2024-12-20T19:40:39.048+02:00 level=INFO source=server.go:555 msg="waiting for llama runner to start responding"
time=2024-12-20T19:40:39.049+02:00 level=INFO source=server.go:589 msg="waiting for server to become available" status="llm server error"
time=2024-12-20T19:40:39.075+02:00 level=INFO source=runner.go:945 msg="starting go runner"
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon RX 7600, compute capability 11.0, VMM: no
time=2024-12-20T19:40:39.670+02:00 level=INFO source=runner.go:946 msg=system info="ROCm : PEER_MAX_BATCH_SIZE = 128 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | AVX512 = 1 | LLAMAFILE = 1 | AARCH64_REPACK = 1 | cgo(gcc)" threads=8
llama_load_model_from_file: using device ROCm0 (AMD Radeon RX 7600) - 7698 MiB free
time=2024-12-20T19:40:39.670+02:00 level=INFO source=.:0 msg="Server listening on 127.0.0.1:37407"
llama_model_loader: loaded meta data with 44 key-value pairs and 464 tensors from /home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models/blobs/sha256-6c2f2196fefaf3eb6df34da11768c8b8646e8434cadc684e53e4d14dddfa2abc (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = gemma2
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = Gemmasutra 9B v1
llama_model_loader: - kv   3:                            general.version str              = v1
llama_model_loader: - kv   4:                       general.organization str              = TheDrummer
llama_model_loader: - kv   5:                           general.basename str              = Gemmasutra
llama_model_loader: - kv   6:                         general.size_label str              = 9B
llama_model_loader: - kv   7:                   general.base_model.count u32              = 2
llama_model_loader: - kv   8:                  general.base_model.0.name str              = Gemma 2 9b It SimPO
llama_model_loader: - kv   9:          general.base_model.0.organization str              = Princeton Nlp
llama_model_loader: - kv  10:              general.base_model.0.repo_url str              = https://huggingface.co/princeton-nlp/...
llama_model_loader: - kv  11:                  general.base_model.1.name str              = Gemmasutra 9B v1
llama_model_loader: - kv  12:               general.base_model.1.version str              = v1
llama_model_loader: - kv  13:          general.base_model.1.organization str              = TheDrummer
llama_model_loader: - kv  14:              general.base_model.1.repo_url str              = https://huggingface.co/TheDrummer/Gem...
llama_model_loader: - kv  15:                               general.tags arr[str,5]       = ["mergekit", "merge", "roleplay", "si...
llama_model_loader: - kv  16:                          general.languages arr[str,1]       = ["en"]
llama_model_loader: - kv  17:                      gemma2.context_length u32              = 8192
llama_model_loader: - kv  18:                    gemma2.embedding_length u32              = 3584
llama_model_loader: - kv  19:                         gemma2.block_count u32              = 42
llama_model_loader: - kv  20:                 gemma2.feed_forward_length u32              = 14336
llama_model_loader: - kv  21:                gemma2.attention.head_count u32              = 16
llama_model_loader: - kv  22:             gemma2.attention.head_count_kv u32              = 8
llama_model_loader: - kv  23:    gemma2.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  24:                gemma2.attention.key_length u32              = 256
llama_model_loader: - kv  25:              gemma2.attention.value_length u32              = 256
llama_model_loader: - kv  26:                          general.file_type u32              = 17
llama_model_loader: - kv  27:              gemma2.attn_logit_softcapping f32              = 50.000000
llama_model_loader: - kv  28:             gemma2.final_logit_softcapping f32              = 30.000000
llama_model_loader: - kv  29:            gemma2.attention.sliding_window u32              = 4096
llama_model_loader: - kv  30:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  31:                         tokenizer.ggml.pre str              = default
llama_model_loader: - kv  32:                      tokenizer.ggml.tokens arr[str,256000]  = ["<pad>", "<eos>", "<bos>", "<unk>", ...
llama_model_loader: - kv  33:                      tokenizer.ggml.scores arr[f32,256000]  = [-1000.000000, -1000.000000, -1000.00...
llama_model_loader: - kv  34:                  tokenizer.ggml.token_type arr[i32,256000]  = [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...
llama_model_loader: - kv  35:                tokenizer.ggml.bos_token_id u32              = 2
llama_model_loader: - kv  36:                tokenizer.ggml.eos_token_id u32              = 1
llama_model_loader: - kv  37:            tokenizer.ggml.unknown_token_id u32              = 3
llama_model_loader: - kv  38:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  39:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  40:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  41:                    tokenizer.chat_template str              = {{ bos_token }}{% if messages[0]['rol...
llama_model_loader: - kv  42:            tokenizer.ggml.add_space_prefix bool             = false
llama_model_loader: - kv  43:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:  169 tensors
llama_model_loader: - type q5_K:  252 tensors
llama_model_loader: - type q6_K:   43 tensors
llm_load_vocab: control token:     45 '<unused38>' is not marked as EOG
llm_load_vocab: control token:     74 '<unused67>' is not marked as EOG
llm_load_vocab: control token:     55 '<unused48>' is not marked as EOG
llm_load_vocab: control token:     99 '<unused92>' is not marked as EOG
llm_load_vocab: control token:    102 '<unused95>' is not marked as EOG
llm_load_vocab: control token:     44 '<unused37>' is not marked as EOG
llm_load_vocab: control token:     26 '<unused19>' is not marked as EOG
llm_load_vocab: control token:     42 '<unused35>' is not marked as EOG
llm_load_vocab: control token:     92 '<unused85>' is not marked as EOG
llm_load_vocab: control token:     90 '<unused83>' is not marked as EOG
llm_load_vocab: control token:    106 '<start_of_turn>' is not marked as EOG
llm_load_vocab: control token:     88 '<unused81>' is not marked as EOG
llm_load_vocab: control token:      5 '<2mass>' is not marked as EOG
llm_load_vocab: control token:    104 '<unused97>' is not marked as EOG
llm_load_vocab: control token:     68 '<unused61>' is not marked as EOG
llm_load_vocab: control token:     94 '<unused87>' is not marked as EOG
llm_load_vocab: control token:     59 '<unused52>' is not marked as EOG
llm_load_vocab: control token:      2 '<bos>' is not marked as EOG
llm_load_vocab: control token:     25 '<unused18>' is not marked as EOG
llm_load_vocab: control token:     93 '<unused86>' is not marked as EOG
llm_load_vocab: control token:     95 '<unused88>' is not marked as EOG
llm_load_vocab: control token:     76 '<unused69>' is not marked as EOG
llm_load_vocab: control token:     97 '<unused90>' is not marked as EOG
llm_load_vocab: control token:     56 '<unused49>' is not marked as EOG
llm_load_vocab: control token:     81 '<unused74>' is not marked as EOG
llm_load_vocab: control token:     13 '<unused6>' is not marked as EOG
llm_load_vocab: control token:     51 '<unused44>' is not marked as EOG
llm_load_vocab: control token:     47 '<unused40>' is not marked as EOG
llm_load_vocab: control token:      8 '<unused1>' is not marked as EOG
llm_load_vocab: control token:    103 '<unused96>' is not marked as EOG
llm_load_vocab: control token:     75 '<unused68>' is not marked as EOG
llm_load_vocab: control token:     79 '<unused72>' is not marked as EOG
llm_load_vocab: control token:     39 '<unused32>' is not marked as EOG
llm_load_vocab: control token:     49 '<unused42>' is not marked as EOG
llm_load_vocab: control token:     41 '<unused34>' is not marked as EOG
llm_load_vocab: control token:     34 '<unused27>' is not marked as EOG
llm_load_vocab: control token:      6 '[@BOS@]' is not marked as EOG
llm_load_vocab: control token:     40 '<unused33>' is not marked as EOG
llm_load_vocab: control token:     33 '<unused26>' is not marked as EOG
llm_load_vocab: control token:     86 '<unused79>' is not marked as EOG
llm_load_vocab: control token:     43 '<unused36>' is not marked as EOG
llm_load_vocab: control token:     35 '<unused28>' is not marked as EOG
llm_load_vocab: control token:     32 '<unused25>' is not marked as EOG
llm_load_vocab: control token:     28 '<unused21>' is not marked as EOG
llm_load_vocab: control token:     19 '<unused12>' is not marked as EOG
llm_load_vocab: control token:     67 '<unused60>' is not marked as EOG
llm_load_vocab: control token:      9 '<unused2>' is not marked as EOG
llm_load_vocab: control token:     52 '<unused45>' is not marked as EOG
llm_load_vocab: control token:     16 '<unused9>' is not marked as EOG
llm_load_vocab: control token:     98 '<unused91>' is not marked as EOG
llm_load_vocab: control token:     80 '<unused73>' is not marked as EOG
llm_load_vocab: control token:     71 '<unused64>' is not marked as EOG
llm_load_vocab: control token:     36 '<unused29>' is not marked as EOG
llm_load_vocab: control token:      0 '<pad>' is not marked as EOG
llm_load_vocab: control token:     11 '<unused4>' is not marked as EOG
llm_load_vocab: control token:     70 '<unused63>' is not marked as EOG
llm_load_vocab: control token:     77 '<unused70>' is not marked as EOG
llm_load_vocab: control token:     64 '<unused57>' is not marked as EOG
llm_load_vocab: control token:     50 '<unused43>' is not marked as EOG
llm_load_vocab: control token:     20 '<unused13>' is not marked as EOG
llm_load_vocab: control token:     73 '<unused66>' is not marked as EOG
llm_load_vocab: control token:     23 '<unused16>' is not marked as EOG
llm_load_vocab: control token:     38 '<unused31>' is not marked as EOG
llm_load_vocab: control token:     21 '<unused14>' is not marked as EOG
llm_load_vocab: control token:     15 '<unused8>' is not marked as EOG
llm_load_vocab: control token:     37 '<unused30>' is not marked as EOG
llm_load_vocab: control token:     14 '<unused7>' is not marked as EOG
llm_load_vocab: control token:     30 '<unused23>' is not marked as EOG
llm_load_vocab: control token:     62 '<unused55>' is not marked as EOG
llm_load_vocab: control token:      3 '<unk>' is not marked as EOG
llm_load_vocab: control token:     18 '<unused11>' is not marked as EOG
time=2024-12-20T19:40:39.801+02:00 level=INFO source=server.go:589 msg="waiting for server to become available" status="llm server loading model"
llm_load_vocab: control token:     22 '<unused15>' is not marked as EOG
llm_load_vocab: control token:     66 '<unused59>' is not marked as EOG
llm_load_vocab: control token:     65 '<unused58>' is not marked as EOG
llm_load_vocab: control token:     10 '<unused3>' is not marked as EOG
llm_load_vocab: control token:    105 '<unused98>' is not marked as EOG
llm_load_vocab: control token:     87 '<unused80>' is not marked as EOG
llm_load_vocab: control token:    100 '<unused93>' is not marked as EOG
llm_load_vocab: control token:     63 '<unused56>' is not marked as EOG
llm_load_vocab: control token:     31 '<unused24>' is not marked as EOG
llm_load_vocab: control token:     58 '<unused51>' is not marked as EOG
llm_load_vocab: control token:     84 '<unused77>' is not marked as EOG
llm_load_vocab: control token:     61 '<unused54>' is not marked as EOG
llm_load_vocab: control token:      1 '<eos>' is not marked as EOG
llm_load_vocab: control token:     60 '<unused53>' is not marked as EOG
llm_load_vocab: control token:     91 '<unused84>' is not marked as EOG
llm_load_vocab: control token:     83 '<unused76>' is not marked as EOG
llm_load_vocab: control token:     85 '<unused78>' is not marked as EOG
llm_load_vocab: control token:     27 '<unused20>' is not marked as EOG
llm_load_vocab: control token:     96 '<unused89>' is not marked as EOG
llm_load_vocab: control token:     72 '<unused65>' is not marked as EOG
llm_load_vocab: control token:     53 '<unused46>' is not marked as EOG
llm_load_vocab: control token:     82 '<unused75>' is not marked as EOG
llm_load_vocab: control token:      7 '<unused0>' is not marked as EOG
llm_load_vocab: control token:      4 '<mask>' is not marked as EOG
llm_load_vocab: control token:    101 '<unused94>' is not marked as EOG
llm_load_vocab: control token:     78 '<unused71>' is not marked as EOG
llm_load_vocab: control token:     89 '<unused82>' is not marked as EOG
llm_load_vocab: control token:     69 '<unused62>' is not marked as EOG
llm_load_vocab: control token:     54 '<unused47>' is not marked as EOG
llm_load_vocab: control token:     57 '<unused50>' is not marked as EOG
llm_load_vocab: control token:     12 '<unused5>' is not marked as EOG
llm_load_vocab: control token:     48 '<unused41>' is not marked as EOG
llm_load_vocab: control token:     17 '<unused10>' is not marked as EOG
llm_load_vocab: control token:     24 '<unused17>' is not marked as EOG
llm_load_vocab: control token:     46 '<unused39>' is not marked as EOG
llm_load_vocab: control token:     29 '<unused22>' is not marked as EOG
llm_load_vocab: special_eos_id is not in special_eog_ids - the tokenizer config may be incorrect
llm_load_vocab: special tokens cache size = 217
llm_load_vocab: token to piece cache size = 1.6014 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = gemma2
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 256000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: vocab_only       = 0
llm_load_print_meta: n_ctx_train      = 8192
llm_load_print_meta: n_embd           = 3584
llm_load_print_meta: n_layer          = 42
llm_load_print_meta: n_head           = 16
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_rot            = 256
llm_load_print_meta: n_swa            = 4096
llm_load_print_meta: n_embd_head_k    = 256
llm_load_print_meta: n_embd_head_v    = 256
llm_load_print_meta: n_gqa            = 2
llm_load_print_meta: n_embd_k_gqa     = 2048
llm_load_print_meta: n_embd_v_gqa     = 2048
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-06
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 2
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_ctx_orig_yarn  = 8192
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: ssm_dt_b_c_rms   = 0
llm_load_print_meta: model type       = 9B
llm_load_print_meta: model ftype      = Q5_K - Medium
llm_load_print_meta: model params     = 9.24 B
llm_load_print_meta: model size       = 6.19 GiB (5.75 BPW) 
llm_load_print_meta: general.name     = Gemmasutra 9B v1
llm_load_print_meta: BOS token        = 2 '<bos>'
llm_load_print_meta: EOS token        = 1 '<eos>'
llm_load_print_meta: EOT token        = 107 '<end_of_turn>'
llm_load_print_meta: UNK token        = 3 '<unk>'
llm_load_print_meta: PAD token        = 0 '<pad>'
llm_load_print_meta: LF token         = 227 '<0x0A>'
llm_load_print_meta: EOG token        = 1 '<eos>'
llm_load_print_meta: EOG token        = 107 '<end_of_turn>'
llm_load_print_meta: max token length = 48
llm_load_tensors: tensor 'token_embd.weight' (q6_K) (and 46 others) cannot be used with preferred buffer type CPU_AARCH64, using CPU instead
llm_load_tensors: offloading 38 repeating layers to GPU
llm_load_tensors: offloaded 38/43 layers to GPU
llm_load_tensors:   CPU_Mapped model buffer size =  6333.65 MiB
llm_load_tensors:        ROCm0 model buffer size =  5066.14 MiB
time=2024-12-20T19:40:40.052+02:00 level=DEBUG source=server.go:600 msg="model load progress 0.20"
time=2024-12-20T19:40:40.303+02:00 level=DEBUG source=server.go:600 msg="model load progress 0.43"
time=2024-12-20T19:40:40.553+02:00 level=DEBUG source=server.go:600 msg="model load progress 0.91"
llama_new_context_with_model: n_seq_max     = 1
llama_new_context_with_model: n_ctx         = 2048
llama_new_context_with_model: n_ctx_per_seq = 2048
llama_new_context_with_model: n_batch       = 512
llama_new_context_with_model: n_ubatch      = 512
llama_new_context_with_model: flash_attn    = 0
llama_new_context_with_model: freq_base     = 10000.0
llama_new_context_with_model: freq_scale    = 1
llama_new_context_with_model: n_ctx_per_seq (2048) < n_ctx_train (8192) -- the full capacity of the model will not be utilized
llama_kv_cache_init:        CPU KV buffer size =    64.00 MiB
llama_kv_cache_init:      ROCm0 KV buffer size =   608.00 MiB
llama_new_context_with_model: KV self size  =  672.00 MiB, K (f16):  336.00 MiB, V (f16):  336.00 MiB
llama_new_context_with_model:        CPU  output buffer size =     0.99 MiB
llama_new_context_with_model:      ROCm0 compute buffer size =  1224.77 MiB
llama_new_context_with_model:  ROCm_Host compute buffer size =    16.01 MiB
llama_new_context_with_model: graph nodes  = 1690
llama_new_context_with_model: graph splits = 56 (with bs=512), 3 (with bs=1)
time=2024-12-20T19:40:40.804+02:00 level=INFO source=server.go:594 msg="llama runner started in 1.76 seconds"
time=2024-12-20T19:40:40.804+02:00 level=DEBUG source=sched.go:462 msg="finished setting up runner" model=/home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models/blobs/sha256-6c2f2196fefaf3eb6df34da11768c8b8646e8434cadc684e53e4d14dddfa2abc
time=2024-12-20T19:40:40.804+02:00 level=DEBUG source=routes.go:1542 msg="chat request" images=0 prompt="<start_of_turn>user\ntest<end_of_turn>\n<start_of_turn>model\n"
time=2024-12-20T19:40:40.804+02:00 level=DEBUG source=routes.go:290 msg="generate request" images=0 prompt="<start_of_turn>user\n\nGenerate a title following these rules:\n    - The title should be based on the prompt at the end\n    - Keep it in the same language as the prompt\n    - The title needs to be less than 30 characters\n    - Use only alphanumeric characters and spaces\n    - Just write the title, NOTHING ELSE\n\n```PROMPT\ntest\n```<end_of_turn>\n<start_of_turn>model\n"
time=2024-12-20T19:40:40.805+02:00 level=DEBUG source=cache.go:104 msg="loading cache slot" id=0 cache=0 prompt=10 used=0 remaining=10
time=2024-12-20T19:40:44.978+02:00 level=DEBUG source=sched.go:466 msg="context for request finished"
time=2024-12-20T19:40:44.978+02:00 level=DEBUG source=sched.go:357 msg="after processing request finished event" modelPath=/home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models/blobs/sha256-6c2f2196fefaf3eb6df34da11768c8b8646e8434cadc684e53e4d14dddfa2abc refCount=1
[GIN] 2024/12/20 - 19:40:44 | 200 |  5.983151608s |       127.0.0.1 | POST     "/api/chat"
time=2024-12-20T19:40:44.979+02:00 level=DEBUG source=cache.go:104 msg="loading cache slot" id=0 cache=63 prompt=83 used=3 remaining=80
time=2024-12-20T19:40:45.389+02:00 level=DEBUG source=server.go:967 msg="new runner detected, loading model for cgo tokenization"
llama_model_loader: loaded meta data with 44 key-value pairs and 464 tensors from /home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models/blobs/sha256-6c2f2196fefaf3eb6df34da11768c8b8646e8434cadc684e53e4d14dddfa2abc (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = gemma2
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = Gemmasutra 9B v1
llama_model_loader: - kv   3:                            general.version str              = v1
llama_model_loader: - kv   4:                       general.organization str              = TheDrummer
llama_model_loader: - kv   5:                           general.basename str              = Gemmasutra
llama_model_loader: - kv   6:                         general.size_label str              = 9B
llama_model_loader: - kv   7:                   general.base_model.count u32              = 2
llama_model_loader: - kv   8:                  general.base_model.0.name str              = Gemma 2 9b It SimPO
llama_model_loader: - kv   9:          general.base_model.0.organization str              = Princeton Nlp
llama_model_loader: - kv  10:              general.base_model.0.repo_url str              = https://huggingface.co/princeton-nlp/...
llama_model_loader: - kv  11:                  general.base_model.1.name str              = Gemmasutra 9B v1
llama_model_loader: - kv  12:               general.base_model.1.version str              = v1
llama_model_loader: - kv  13:          general.base_model.1.organization str              = TheDrummer
llama_model_loader: - kv  14:              general.base_model.1.repo_url str              = https://huggingface.co/TheDrummer/Gem...
llama_model_loader: - kv  15:                               general.tags arr[str,5]       = ["mergekit", "merge", "roleplay", "si...
llama_model_loader: - kv  16:                          general.languages arr[str,1]       = ["en"]
llama_model_loader: - kv  17:                      gemma2.context_length u32              = 8192
llama_model_loader: - kv  18:                    gemma2.embedding_length u32              = 3584
llama_model_loader: - kv  19:                         gemma2.block_count u32              = 42
llama_model_loader: - kv  20:                 gemma2.feed_forward_length u32              = 14336
llama_model_loader: - kv  21:                gemma2.attention.head_count u32              = 16
llama_model_loader: - kv  22:             gemma2.attention.head_count_kv u32              = 8
llama_model_loader: - kv  23:    gemma2.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  24:                gemma2.attention.key_length u32              = 256
llama_model_loader: - kv  25:              gemma2.attention.value_length u32              = 256
llama_model_loader: - kv  26:                          general.file_type u32              = 17
llama_model_loader: - kv  27:              gemma2.attn_logit_softcapping f32              = 50.000000
llama_model_loader: - kv  28:             gemma2.final_logit_softcapping f32              = 30.000000
llama_model_loader: - kv  29:            gemma2.attention.sliding_window u32              = 4096
llama_model_loader: - kv  30:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  31:                         tokenizer.ggml.pre str              = default
llama_model_loader: - kv  32:                      tokenizer.ggml.tokens arr[str,256000]  = ["<pad>", "<eos>", "<bos>", "<unk>", ...
llama_model_loader: - kv  33:                      tokenizer.ggml.scores arr[f32,256000]  = [-1000.000000, -1000.000000, -1000.00...
llama_model_loader: - kv  34:                  tokenizer.ggml.token_type arr[i32,256000]  = [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...
llama_model_loader: - kv  35:                tokenizer.ggml.bos_token_id u32              = 2
llama_model_loader: - kv  36:                tokenizer.ggml.eos_token_id u32              = 1
llama_model_loader: - kv  37:            tokenizer.ggml.unknown_token_id u32              = 3
llama_model_loader: - kv  38:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  39:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  40:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  41:                    tokenizer.chat_template str              = {{ bos_token }}{% if messages[0]['rol...
llama_model_loader: - kv  42:            tokenizer.ggml.add_space_prefix bool             = false
llama_model_loader: - kv  43:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:  169 tensors
llama_model_loader: - type q5_K:  252 tensors
llama_model_loader: - type q6_K:   43 tensors
llm_load_vocab: special_eos_id is not in special_eog_ids - the tokenizer config may be incorrect
llm_load_vocab: special tokens cache size = 217
llm_load_vocab: token to piece cache size = 1.6014 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = gemma2
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 256000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: vocab_only       = 1
llm_load_print_meta: model type       = ?B
llm_load_print_meta: model ftype      = all F32
llm_load_print_meta: model params     = 9.24 B
llm_load_print_meta: model size       = 6.19 GiB (5.75 BPW) 
llm_load_print_meta: general.name     = Gemmasutra 9B v1
llm_load_print_meta: BOS token        = 2 '<bos>'
llm_load_print_meta: EOS token        = 1 '<eos>'
llm_load_print_meta: EOT token        = 107 '<end_of_turn>'
llm_load_print_meta: UNK token        = 3 '<unk>'
llm_load_print_meta: PAD token        = 0 '<pad>'
llm_load_print_meta: LF token         = 227 '<0x0A>'
llm_load_print_meta: EOG token        = 1 '<eos>'
llm_load_print_meta: EOG token        = 107 '<end_of_turn>'
llm_load_print_meta: max token length = 48
llama_model_load: vocab only - skipping tensors
[GIN] 2024/12/20 - 19:40:45 | 200 |   6.53852533s |       127.0.0.1 | POST     "/api/generate"
time=2024-12-20T19:40:45.534+02:00 level=DEBUG source=sched.go:407 msg="context for request finished"
time=2024-12-20T19:40:45.534+02:00 level=DEBUG source=sched.go:339 msg="runner with non-zero duration has gone idle, adding timer" modelPath=/home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models/blobs/sha256-6c2f2196fefaf3eb6df34da11768c8b8646e8434cadc684e53e4d14dddfa2abc duration=5m0s
time=2024-12-20T19:40:45.534+02:00 level=DEBUG source=sched.go:357 msg="after processing request finished event" modelPath=/home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models/blobs/sha256-6c2f2196fefaf3eb6df34da11768c8b8646e8434cadc684e53e4d14dddfa2abc refCount=0
time=2024-12-20T19:40:52.778+02:00 level=DEBUG source=sched.go:575 msg="evaluating already loaded" model=/home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models/blobs/sha256-6c2f2196fefaf3eb6df34da11768c8b8646e8434cadc684e53e4d14dddfa2abc
time=2024-12-20T19:40:52.780+02:00 level=DEBUG source=routes.go:1542 msg="chat request" images=0 prompt="<start_of_turn>user\ntest<end_of_turn>\n<start_of_turn>model\n<span>Please</span><span> provide</span><span> a</span><span> test</span><span> case</span><span> or</span><span> question</span><span> so</span><span> I</span><span> can</span><span> demonstrate</span><span> my</span><span> abilities</span><span>.</span><span> I</span><span>&apos;</span><span>m</span><span> ready</span><span> to</span><span> assist</span><span> with</span><span> various</span><span> tasks</span><span> like</span><span> answering</span><span> questions</span><span>,</span><span> generating</span><span> creative</span><span> content</span><span>,</span><span> translating</span><span> languages</span><span>,</span><span> summarizing</span><span> text</span><span>,</span><span> and</span><span> more</span><span>.</span><span> Just</span><span> let</span><span> me</span><span> know</span><span> what</span><span> you</span><span>&apos;</span><span>d</span><span> like</span><span> me</span><span> to</span><span> do</span><span>!</span><end_of_turn>\n<start_of_turn>user\nwtf?<end_of_turn>\n<start_of_turn>model\n"
time=2024-12-20T19:40:52.781+02:00 level=DEBUG source=cache.go:104 msg="loading cache slot" id=0 cache=85 prompt=328 used=3 remaining=325
[GIN] 2024/12/20 - 19:41:02 | 200 | 10.068386048s |       127.0.0.1 | POST     "/api/chat"
time=2024-12-20T19:41:02.830+02:00 level=DEBUG source=sched.go:407 msg="context for request finished"
time=2024-12-20T19:41:02.830+02:00 level=DEBUG source=sched.go:339 msg="runner with non-zero duration has gone idle, adding timer" modelPath=/home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models/blobs/sha256-6c2f2196fefaf3eb6df34da11768c8b8646e8434cadc684e53e4d14dddfa2abc duration=5m0s
time=2024-12-20T19:41:02.830+02:00 level=DEBUG source=sched.go:357 msg="after processing request finished event" modelPath=/home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models/blobs/sha256-6c2f2196fefaf3eb6df34da11768c8b8646e8434cadc684e53e4d14dddfa2abc refCount=0
time=2024-12-20T19:41:25.573+02:00 level=DEBUG source=sched.go:575 msg="evaluating already loaded" model=/home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models/blobs/sha256-6c2f2196fefaf3eb6df34da11768c8b8646e8434cadc684e53e4d14dddfa2abc
time=2024-12-20T19:41:25.574+02:00 level=DEBUG source=routes.go:1542 msg="chat request" images=0 prompt="<start_of_turn>user\ntell me about quantum teleportation<end_of_turn>\n<start_of_turn>model\n"
time=2024-12-20T19:41:25.574+02:00 level=DEBUG source=cache.go:104 msg="loading cache slot" id=0 cache=446 prompt=15 used=4 remaining=11
time=2024-12-20T19:41:25.574+02:00 level=DEBUG source=sched.go:575 msg="evaluating already loaded" model=/home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models/blobs/sha256-6c2f2196fefaf3eb6df34da11768c8b8646e8434cadc684e53e4d14dddfa2abc
time=2024-12-20T19:41:25.574+02:00 level=DEBUG source=routes.go:290 msg="generate request" images=0 prompt="<start_of_turn>user\n\nGenerate a title following these rules:\n    - The title should be based on the prompt at the end\n    - Keep it in the same language as the prompt\n    - The title needs to be less than 30 characters\n    - Use only alphanumeric characters and spaces\n    - Just write the title, NOTHING ELSE\n\n```PROMPT\ntell me about quantum teleportation\n```<end_of_turn>\n<start_of_turn>model\n"
[GIN] 2024/12/20 - 19:41:58 | 200 | 32.587035812s |       127.0.0.1 | POST     "/api/chat"
time=2024-12-20T19:41:58.144+02:00 level=DEBUG source=sched.go:407 msg="context for request finished"
time=2024-12-20T19:41:58.144+02:00 level=DEBUG source=sched.go:357 msg="after processing request finished event" modelPath=/home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models/blobs/sha256-6c2f2196fefaf3eb6df34da11768c8b8646e8434cadc684e53e4d14dddfa2abc refCount=1
time=2024-12-20T19:41:58.145+02:00 level=DEBUG source=cache.go:104 msg="loading cache slot" id=0 cache=520 prompt=88 used=3 remaining=85
[GIN] 2024/12/20 - 19:41:58 | 200 | 33.109442447s |       127.0.0.1 | POST     "/api/generate"
time=2024-12-20T19:41:58.666+02:00 level=DEBUG source=sched.go:407 msg="context for request finished"
time=2024-12-20T19:41:58.667+02:00 level=DEBUG source=sched.go:339 msg="runner with non-zero duration has gone idle, adding timer" modelPath=/home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models/blobs/sha256-6c2f2196fefaf3eb6df34da11768c8b8646e8434cadc684e53e4d14dddfa2abc duration=5m0s
time=2024-12-20T19:41:58.667+02:00 level=DEBUG source=sched.go:357 msg="after processing request finished event" modelPath=/home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models/blobs/sha256-6c2f2196fefaf3eb6df34da11768c8b8646e8434cadc684e53e4d14dddfa2abc refCount=0
time=2024-12-20T19:42:09.030+02:00 level=DEBUG source=sched.go:575 msg="evaluating already loaded" model=/home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models/blobs/sha256-6c2f2196fefaf3eb6df34da11768c8b8646e8434cadc684e53e4d14dddfa2abc
time=2024-12-20T19:42:09.030+02:00 level=DEBUG source=sched.go:575 msg="evaluating already loaded" model=/home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models/blobs/sha256-6c2f2196fefaf3eb6df34da11768c8b8646e8434cadc684e53e4d14dddfa2abc
time=2024-12-20T19:42:09.030+02:00 level=DEBUG source=routes.go:1542 msg="chat request" images=0 prompt="<start_of_turn>user\ntell a joke<end_of_turn>\n<start_of_turn>model\n"
time=2024-12-20T19:42:09.030+02:00 level=DEBUG source=routes.go:290 msg="generate request" images=0 prompt="<start_of_turn>user\n\nGenerate a title following these rules:\n    - The title should be based on the prompt at the end\n    - Keep it in the same language as the prompt\n    - The title needs to be less than 30 characters\n    - Use only alphanumeric characters and spaces\n    - Just write the title, NOTHING ELSE\n\n```PROMPT\ntell a joke\n```<end_of_turn>\n<start_of_turn>model\n"
time=2024-12-20T19:42:09.031+02:00 level=DEBUG source=cache.go:104 msg="loading cache slot" id=0 cache=92 prompt=12 used=3 remaining=9
time=2024-12-20T19:42:10.128+02:00 level=DEBUG source=sched.go:407 msg="context for request finished"
[GIN] 2024/12/20 - 19:42:10 | 200 |  1.115457003s |       127.0.0.1 | POST     "/api/chat"
time=2024-12-20T19:42:10.128+02:00 level=DEBUG source=sched.go:357 msg="after processing request finished event" modelPath=/home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models/blobs/sha256-6c2f2196fefaf3eb6df34da11768c8b8646e8434cadc684e53e4d14dddfa2abc refCount=1
time=2024-12-20T19:42:10.129+02:00 level=DEBUG source=cache.go:104 msg="loading cache slot" id=0 cache=28 prompt=85 used=3 remaining=82
[GIN] 2024/12/20 - 19:42:10 | 200 |  1.519878496s |       127.0.0.1 | POST     "/api/generate"
time=2024-12-20T19:42:10.532+02:00 level=DEBUG source=sched.go:407 msg="context for request finished"
time=2024-12-20T19:42:10.532+02:00 level=DEBUG source=sched.go:339 msg="runner with non-zero duration has gone idle, adding timer" modelPath=/home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models/blobs/sha256-6c2f2196fefaf3eb6df34da11768c8b8646e8434cadc684e53e4d14dddfa2abc duration=5m0s
time=2024-12-20T19:42:10.532+02:00 level=DEBUG source=sched.go:357 msg="after processing request finished event" modelPath=/home/kitsune/.local/share/com.jeffser.Alpaca/.ollama/models/blobs/sha256-6c2f2196fefaf3eb6df34da11768c8b8646e8434cadc684e53e4d14dddfa2abc refCount=0

```

**Comment by deadYokai** [comment]
sometimes html escape characters also appears, but it's rare

**Comment by deadYokai** [comment]
this line add `span` tags, and i can assume is a some markup error occures

https://github.com/Jeffser/Alpaca/blob/3befd27ad7c9be47c8c68edaf7e5e95424f7e2e0/src/custom_widgets/message_widget.py#L533

**Comment by robinehren** [comment]
I second this, but for me there is something in addition to that. Continuing an already existing conversation results in the same issue as @deadYokai described. However, starting a new chat results in an empty answer. I see the answer generating but the rendering fails. 

The error I receive is:
`(python3:2): Gtk-WARNING **: 14:58:13.410: Failed to set text: '.[answer to my promt as html]' from markup due to error parsing markup: Error on line 3 char 66: Element “span” was closed, but the currently open element is “b”`

![image](https://github.com/user-attachments/assets/b746acc6-4199-4445-9ef6-baeff499cdaa)

I am running V3.0.0

**Comment by Ayanami-Rin** [comment]
I have this on the flatpak release, as well.
If I edit the response, I see that every space between words has been replaced with span tag pairs...
![image](https://github.com/user-attachments/assets/c0a48661-5203-451e-8e3f-a7f85a02249b)
![image](https://github.com/user-attachments/assets/95516957-c559-4331-bca1-bf246ad67977)

**Comment by Jeffser** [comment]
Hi I just fixed this

https://github.com/Jeffser/Alpaca/commit/689361cee4d3f731598cfa2b1beab353e81888d0

I'm preparing a quick 3.0.1 release

**Comment by Jeffser** [comment]
3.0.1 is available on Flathub!

I'll close this issue but if you still have the same problem feel free to reopen it.
